### PR TITLE
WIP: Offline Camp Oregon 2019

### PR DESCRIPTION
**Pull request by kidfribble**
I archived 2017 Oregon files, made temp language replacements, updated the typeform url, and commented out schedule for the time being. When I have updated CoC text (if it exists - if not I can write the updates in for review) and FAQ, I'll add those to this.

### CODE REVIEW

**Comment by terichadbourne** [comment]
@kidfribble I think you may have made your CoC and FAQ changes to the docs in the `oregon-2017` folder instead of the 2019 site. Am I reading that right?

**Comment by kidfribble** [comment]
@terichadbourne whoops - good catch!

**Comment by terichadbourne** [comment]
@kidfribble Do you want me to try to move those edits to the right (2019) files and revert the changes to the 2017 docs? Or are you already working on that fix? 

Stuff we need to do before merging this: 
- [x] revert CoC change from 2017 archive and move to 2019 site
- [x] revert FAQ change from 2017 archive and move to 2019 site
- [ ] confirm budget and add final pricing to Typeform (see Slack)
- [x] put pricing back on website (apply now to qualify for X early bird rate)
- [x] add updated sponsor prospectus 
- [x] move Protocol Labs to room sponsor section
- [ ] ask @bradley-holt & @crtr0 to proof final draft

**Comment by terichadbourne** [comment]
@kidfribble Thanks for all the work on this. Proofing now and see these little bugs or areas for potential improvement. Let me know if you disagree on any of these suggestions.

Anything marked with a 🙅‍♀️ is something I think you should be the one doing. Other stuff I could potentially take care of if you're more strapped for time than I am. Let me know what works.

- 🙅‍♀️ The sponsor prospectus should show a 4 crossed out with a 3 next to it under room sponsors.
image

- 🙅‍♀️ We should pick a version of the PL logo that includes the words Protocol Labs for better brand recognition. That press kit offers a variety of formats so you can pick whichever shape you prefer that includes the words.
image

- 🙅‍♀️ I think we should probably shrink the font for the pronouns on the organizer page but was leaving this to your design judgement when I implemented it originally: 

image

- My phone number in the CoC is outdated as I no longer have my IBM phone. Let's use my Google Voice number for this in case of spam from being posted: 857-626-6205.

- Some of the buttons say "Attend" and some say "Apply." I assume we want "Apply", right?  This is something that's always been easy to miss because they live in so many different files. Here's the current button inventory.

   - top right of homepage - currently attend
   - halfway down homepage - currently apply + text we'll need to update
   - bottom of homepage - currently attend + text we'll need to update
   - top right of other pages - currently apply 
   - midway down other pages - currently apply  + text we'll need to update
   - bottom of other pages - currently apply + text we'll need to update

- The text on those midway and bottom ones will need to be changed to include the rate and highlight the availability of scholarships. For example, if people approve the current budget: 

    `<p>Apply by May 31 to receive the Super Early Bird rate of $350 (includes food and lodging). <a style="color:#FF99C6;" href= "{{ page.root_path }}camp/faq.html#scholarships">Scholarships available.</a></p>`

- The Offline First newsletter is either on hiatus or defunct, so I'd recommend we remove the signup unless we're prepared to start something ourselves: 
image

- Typo of "August" on FAQ page: 
image

- Are we leaving the reference to s'mores despite not having a good way to make them? Doing it in the indoor stove at 90 degrees?
image

- Need to delete the first two paragraphs here: 
image

- Add 2019 to event name: 
image

- Reduce regular price from $600 to $500 if team agrees with my budget proposal: 
image

- Update sponsor link to go to new prospectus: 
image

- Note that the scholarship fund (link above) is still feeding money to M&M if anyone donates. We'll need to update and provide a new link when we have a new fiscal sponsor. 

- Same two issues as noted above with the links in the diversity section: 
image


These suggestions apply only to the 2017 archive so are less urgent: 
- 🙅‍♀️ relative paths are broken so there's no styling, subpages can't load, etc.
- 🙅‍♀️ FAQ and CoC should be reverted for an accurate historical record

**Comment by kidfribble** [comment]
@terichadbourne the only thing not changed from above is:

* Note that the scholarship fund (link above) is still feeding money to M&M if anyone donates. We'll need to update and provide a new link when we have a new fiscal sponsor.

I'm not sure what to do about this right now. We can't hold the money in Ti.To?

**Comment by terichadbourne** [comment]
@kidfribble If you want to ensure you don't get any money funneled to you, we could remove the option to donate to the fund (listed here on the website and in the Typeform application) temporarily until we (hopefully) get set up with Technocation. I assume we'll lose at least a week or two to getting set up with a bank account and connecting Tito to it. Would you prefer that?  (No, I don't think Tito will hold money.)

**Comment by terichadbourne** [comment]
@kidfribble I just removed the links to the scholarship and put "(coming soon)" notes by those references. 

The phone number in the written driving directions (/camp/assets/directions-to-offline-camp-oregon.pdf) is old so I'll need to redo that PDF and update the links to it from the FAQ, but I don't consider that urgent. 

I made a few small wording changes throughout (mostly FAQ) where I found more outdated info or found ways to seem more beginner friendly. 

Let me know what you think of the layout on the team page now. I slightly tweaked the CSS so it shows 2 across instead of 3 (which is nicely balanced while we have 4 people) and wraps to stacked on mobile. Previously it was staying at 3 across the top and one on bottom and shrinking the images very small to keep that layout. If you hate this plan I can revert it for you.

**Comment by crtr0** [comment]
One the `/camp` page:

> We’re developers interested in making our apps work without constant internet connection. 

should be

> We’re developers interested in making our apps work without *a* constant internet connection.

**Comment by terichadbourne** [comment]
Just fixed that @crtr0. 

@bradley-holt are you still proofing? 

@kidfribble Let me know if there's anything in my last two little commits you don't like - it's mostly cleanup.

From my perspective the things remaining to do to the site before we merge and launch are: 

- [ ] Finish our discussion about early birds / application process in Slack and update the site and Typform to match 
- [x] Fix the phone number on the directions PDF (@bradley-holt is working on this)
- [ ] Agree on when to launch (I'd propose Monday if we're ready by then and we have a reasonable plan for announcing, otherwise later next week.)
- [x] Update offlinefirst.org/events with Oregon details

**Comment by bradley-holt** [comment]
@terichadbourne LGTM! My only very minor comments:

On the FAQ page, I would suggest striking part of this:

>~those who identify as~ members of groups typically underrepresented at tech events

Also, should we assert that we will not be identifying scholarship recipients to other campers? For example:

>Scholarships recipients will not be identified to other campers.

**Comment by terichadbourne** [comment]
@bradley-holt I'd be comfortable with that first change. 

Where in the current phrasing (I assume somewhere in the scholarship section) were you thinking of adding that new statement? If we include it, I'd love to make it better fit the casual tone. 

Maybe adding something like this to the end of the section? 

`Please don't let your financial circumstances keep you from applying to camp. Just reach out with any questions. (And don't worry, how much you pay to attend Offline Camp is just between us.)`

**Comment by bradley-holt** [comment]
@terichadbourne Works for me.

**Comment by terichadbourne** [comment]
I just updated pricing /early bird stuff and made some changes to the FAQ to make it easier to navigate. @bradley-holt or @kidfribble could you please take a look? I think this gets us to a point I'm comfortable with for launch.

**Comment by bradley-holt** [comment]
@terichadbourne LGTM

**Pull request merged**
