### PR TITLE
Update with Offline Camp West Info

### PR DESCRIPTION
**Pull request by mmcelaney**

### CODE REVIEW

**Comment by gr2m** [comment]
- let’s remove the campers section for now on the camp landing page
- maybe we can replace the image?

**Comment by mmcelaney** [comment]
oh yeah, i didn’t know which image to choose and also didn’t know how we are hosting images on the site

**Comment by gr2m** [comment]
I can check it tonight :)

**Comment by gr2m** [comment]
@mmcelaney https://github.com/offlinefirst/offlinefirst.org/pull/48/commits/b6f0e6fff6fbce6a4a7501992e233f4f64e4840a The images are in the images folder. Note that all new assets like images have also to be listed in the `cache.manifest` file, otherwise they will not loaded

**Comment by gr2m** [comment]
preview

screen shot 2016-08-22 at 20 00 54

**Pull request merged**
